name: deploy

on:
  push:
    branches: master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Ckeckout code
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: yarn --pure-lockfile

      - name: Build
        run: yarn run build --no-lint --prod

      - name: Deploy
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        run: yarn run firebase deploy
